#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

/*Needed variables*/
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ICU driver as required.
▪ Set up the ICU callback function.
▪ Set the direction for the trigger pin as output through
the GPIO driver.
*/
void Ultrasonic_init(void)
{
	/* Create configuration structure for ICU driver */
	ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};
	ICU_init(&ICU_Configurations);
	/*Set up the ICU callback function.*/
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*Set the direction for the trigger pin as output through the GPIO driver.*/
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);
}

/*
 * Description :
 * Send the trigger pulse to the ultrasonic sensor.
*/
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * Description :
 * Send the trigger pulse by using the Ultrasonic_Trigger function.
▪ Start the measurement process via the ICU driver.
*/
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance=0;
	g_timeHigh=0;
	/*Send the trigger pulse by using the Ultrasonic_Trigger function to start measure.*/
	Ultrasonic_Trigger();
	/*Start the measurement process via the ICU driver.*/
	//wait to measure
	while(g_edgeCount!=2)
	{}
	 //+1 is added to adjust calibration with proteus simulation
	distance = (uint16)((float32)g_timeHigh/117.647)+1;
	//remove added one for calibration
	if(distance<3)
	{
		distance=0;
	}
	g_edgeCount=0; 	// to be ready to measure again
	return distance;
}

/*
 * Description :
 * This is the callback function called by the ICU driver.
▪ It calculates the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		//Clear time to start measure pulse time
		ICU_clearTimerValue();
		//Change to falling edge to detect it
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		//Get the measured time
		g_timeHigh = ICU_getInputCaptureValue();
		//Clear time to be ready to measure again
		ICU_clearTimerValue();
		//Change to raising edge to be ready to measure again
		ICU_setEdgeDetectionType(RAISING);
	}
}
